# Generated by Django 3.2.5 on 2021-08-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taste',
            name='product',
            field=models.ManyToManyField(through='products.ProductTaste', to='products.Product'),
        ),
    ]
